Release 2.01
  * Changed the configure system to install the LZO library under the
    name "liblzo2" so that parallel installation with LZO v1 is possible.
  * Improved auto-configuration in miniLZO for some embedded targets like
    Blackfin and H8/300 processors.

diff --git a/autoconf/shtool b/autoconf/shtool
--- a/autoconf/shtool
+++ b/autoconf/shtool
@@ -1,12 +1,12 @@
 #!/bin/sh
 ##
 ##  GNU shtool -- The GNU Portable Shell Tool
-##  Copyright (c) 1994-2004 Ralf S. Engelschall <rse@engelschall.com>
+##  Copyright (c) 1994-2005 Ralf S. Engelschall <rse@engelschall.com>
 ##
 ##  See http://www.gnu.org/software/shtool/ for more information.
 ##  See ftp://ftp.gnu.org/gnu/shtool/ for latest version.
 ##
-##  Version:  2.0.1 (11-Aug-2004)
+##  Version:  2.0.2 (15-Jun-2005)
 ##  Contents: all available modules
 ##
 
@@ -65,8 +65,8 @@ if [ $# -eq 0 ]; then
     exit 1
 fi
 if [ ".$1" = ".-h" ] || [ ".$1" = ".--help" ]; then
-    echo "This is GNU shtool, version 2.0.1 (11-Aug-2004)"
-    echo "Copyright (c) 1994-2004 Ralf S. Engelschall <rse@engelschall.com>"
+    echo "This is GNU shtool, version 2.0.2 (15-Jun-2005)"
+    echo "Copyright (c) 1994-2005 Ralf S. Engelschall <rse@engelschall.com>"
     echo "Report bugs to <bug-shtool@gnu.org>"
     echo ''
     echo "Usage: shtool [<options>] [<cmd-name> [<cmd-options>] [<cmd-args>]]"
@@ -132,7 +132,7 @@ if [ ".$1" = ".-h" ] || [ ".$1" = ".--help" ]; then
     exit 0
 fi
 if [ ".$1" = ".-v" ] || [ ".$1" = ".--version" ]; then
-    echo "GNU shtool 2.0.1 (11-Aug-2004)"
+    echo "GNU shtool 2.0.2 (15-Jun-2005)"
     exit 0
 fi
 if [ ".$1" = ".-r" ] || [ ".$1" = ".--recreate" ]; then
@@ -571,6 +571,7 @@ esac
 
 #   establish a temporary file on request
 if [ ".$gen_tmpfile" = .yes ]; then
+    #   create (explicitly) secure temporary directory
     if [ ".$TMPDIR" != . ]; then
         tmpdir="$TMPDIR"
     elif [ ".$TEMPDIR" != . ]; then
@@ -578,10 +579,19 @@ if [ ".$gen_tmpfile" = .yes ]; then
     else
         tmpdir="/tmp"
     fi
-    tmpfile="$tmpdir/.shtool.$$"
-    rm -f $tmpfile >/dev/null 2>&1
-    touch $tmpfile
-    chmod 600 $tmpfile
+    tmpdir="$tmpdir/.shtool.$$"
+    ( umask 077
+      rm -rf "$tmpdir" >/dev/null 2>&1 || true
+      mkdir  "$tmpdir" >/dev/null 2>&1
+      if [ $? -ne 0 ]; then
+          echo "$msgprefix:Error: failed to create temporary directory \`$tmpdir'" 1>&2
+          exit 1
+      fi
+    )
+
+    #   create (implicitly) secure temporary file
+    tmpfile="$tmpdir/shtool.tmp"
+    touch "$tmpfile"
 fi
 
 #   utility function: map string to lower case
@@ -598,7 +608,7 @@ util_upper () {
 shtool_exit () {
     rc="$1"
     if [ ".$gen_tmpfile" = .yes ]; then
-        rm -f $tmpfile >/dev/null 2>&1 || true
+        rm -rf "$tmpdir" >/dev/null 2>&1 || true
     fi
     exit $rc
 }
@@ -612,7 +622,7 @@ case $tool in
 echo )
     ##
     ##  echo -- Print string with optional construct expansion
-    ##  Copyright (c) 1998-2004 Ralf S. Engelschall <rse@engelschall.com>
+    ##  Copyright (c) 1998-2005 Ralf S. Engelschall <rse@engelschall.com>
     ##
 
     text="$*"
@@ -911,7 +921,7 @@ mdate )
     ##
     ##  mdate -- Pretty-print modification time of a file or dir
     ##  Copyright (c) 1995-1997 Free Software Foundation, Inc.
-    ##  Copyright (c) 1998-2004 Ralf S. Engelschall <rse@engelschall.com>
+    ##  Copyright (c) 1998-2005 Ralf S. Engelschall <rse@engelschall.com>
     ##
 
     fod="$1"
@@ -1036,7 +1046,7 @@ mdate )
 table )
     ##
     ##  table -- Pretty-print a field-separated list as a table
-    ##  Copyright (c) 1998-2004 Ralf S. Engelschall <rse@engelschall.com>
+    ##  Copyright (c) 1998-2005 Ralf S. Engelschall <rse@engelschall.com>
     ##
 
     if [ $opt_c -gt 4 ]; then
@@ -1101,7 +1111,7 @@ table )
 prop )
     ##
     ##  prop -- Display progress with a running propeller
-    ##  Copyright (c) 1998-2004 Ralf S. Engelschall <rse@engelschall.com>
+    ##  Copyright (c) 1998-2005 Ralf S. Engelschall <rse@engelschall.com>
     ##
 
     perl=''
@@ -1147,7 +1157,7 @@ prop )
 move )
     ##
     ##  move -- Move files with simultaneous substitution
-    ##  Copyright (c) 1999-2004 Ralf S. Engelschall <rse@engelschall.com>
+    ##  Copyright (c) 1999-2005 Ralf S. Engelschall <rse@engelschall.com>
     ##
 
     src="$1"
@@ -1239,7 +1249,7 @@ move )
 install )
     ##
     ##  install -- Install a program, script or datafile
-    ##  Copyright (c) 1997-2004 Ralf S. Engelschall <rse@engelschall.com>
+    ##  Copyright (c) 1997-2005 Ralf S. Engelschall <rse@engelschall.com>
     ##
 
     #   special case: "shtool install -d <dir> [...]" internally
@@ -1402,7 +1412,7 @@ install )
 mkdir )
     ##
     ##  mkdir -- Make one or more directories
-    ##  Copyright (c) 1996-2004 Ralf S. Engelschall <rse@engelschall.com>
+    ##  Copyright (c) 1996-2005 Ralf S. Engelschall <rse@engelschall.com>
     ##
 
     errstatus=0
@@ -1490,7 +1500,7 @@ mkdir )
 mkln )
     ##
     ##  mkln -- Make link with calculation of relative paths
-    ##  Copyright (c) 1998-2004 Ralf S. Engelschall <rse@engelschall.com>
+    ##  Copyright (c) 1998-2005 Ralf S. Engelschall <rse@engelschall.com>
     ##
 
     #   determine source(s) and destination
@@ -1641,7 +1651,7 @@ mkln )
 mkshadow )
     ##
     ##  mkshadow -- Make a shadow tree through symbolic links
-    ##  Copyright (c) 1998-2004 Ralf S. Engelschall <rse@engelschall.com>
+    ##  Copyright (c) 1998-2005 Ralf S. Engelschall <rse@engelschall.com>
     ##
 
     #   source and destination directory
@@ -1759,7 +1769,7 @@ mkshadow )
 fixperm )
     ##
     ##  fixperm -- Fix file permissions inside a source tree
-    ##  Copyright (c) 1996-2004 Ralf S. Engelschall <rse@engelschall.com>
+    ##  Copyright (c) 1996-2005 Ralf S. Engelschall <rse@engelschall.com>
     ##
 
     paths="$*"
@@ -1816,7 +1826,7 @@ fixperm )
 rotate )
     ##
     ##  rotate -- Logfile rotation
-    ##  Copyright (c) 2001-2004 Ralf S. Engelschall <rse@engelschall.com>
+    ##  Copyright (c) 2001-2005 Ralf S. Engelschall <rse@engelschall.com>
     ##
 
     #   make sure we have at least one file to rotate
@@ -2180,7 +2190,7 @@ rotate )
 tarball )
     ##
     ##  tarball -- Roll distribution tarballs
-    ##  Copyright (c) 1999-2004 Ralf S. Engelschall <rse@engelschall.com>
+    ##  Copyright (c) 1999-2005 Ralf S. Engelschall <rse@engelschall.com>
     ##
 
     srcs="$*"
@@ -2344,7 +2354,7 @@ tarball )
 subst )
     ##
     ##  subst -- Apply sed(1) substitution operations
-    ##  Copyright (c) 2001-2004 Ralf S. Engelschall <rse@engelschall.com>
+    ##  Copyright (c) 2001-2005 Ralf S. Engelschall <rse@engelschall.com>
     ##
 
     #   remember optional list of file(s)
@@ -2505,7 +2515,7 @@ subst )
 platform )
     ##
     ##  platform -- Platform Identification Utility
-    ##  Copyright (c) 2003-2004 Ralf S. Engelschall <rse@engelschall.com>
+    ##  Copyright (c) 2003-2005 Ralf S. Engelschall <rse@engelschall.com>
     ##
 
     #   option post-processing
@@ -2684,7 +2694,7 @@ platform )
             if [ ".$SP" = . ]; then
                 for tagfile in x \
                     `cd /etc && \
-                    /bin/ls *[_-]release *[_-]version 2>/dev/null | \
+                    /bin/ls *[_-]release *[_-]version 2>/dev/null | sort | \
                     sed -e '/^redhat-release$/d' -e '/^lsb-release$/d'; \
                     echo redhat-release lsb-release`
                 do
@@ -2705,15 +2715,16 @@ platform )
                                 n="<R>ed <H>at <L>inux"
                             fi
                             ;;
-                        debian      ) n="Debian[ GNU/Linux]"        ;;
-                        fedora      ) n="<Fedora> Core[ GNU/Linux]" ;;
-                        suse        ) n="SuSE[ Linux]"              ;;
-                        mandrake    ) n="Mandrake[ Linux]"          ;;
-                        gentoo      ) n="Gentoo[ GNU/Linux]"        ;;
-                        slackware   ) n="Slackware[ Linux]"         ;;
-                        turbolinux  ) n="TurboLinux"                ;;
-                        unitedlinux ) n="UnitedLinux"               ;;
-                        *           ) n="${n}[ GNU/Linux]"          ;;
+                        debian            ) n="Debian[ GNU/Linux]"        ;;
+                        ubuntu            ) n="Ubuntu[ GNU/Linux]"        ;;
+                        fedora            ) n="<Fedora> Core[ GNU/Linux]" ;;
+                        suse              ) n="SuSE[ Linux]"              ;;
+                        mandrake|mandriva ) n="Mandriva[ Linux]"          ;;
+                        gentoo            ) n="Gentoo[ GNU/Linux]"        ;;
+                        slackware         ) n="Slackware[ Linux]"         ;;
+                        turbolinux        ) n="TurboLinux"                ;;
+                        unitedlinux       ) n="UnitedLinux"               ;;
+                        *                 ) n="${n}[ GNU/Linux]"          ;;
                     esac
                     case "$n" in
                         *"<"*">"* ) SP="$n <$v>" ;;
@@ -2868,11 +2879,14 @@ platform )
                 if [ ".`/usr/sbin/lsattr -El ${cpu_id} | grep -i powerpc`" != . ]; then
                     cpu_arch=powerpc
                 fi
+            elif [ -d /QOpenSys ]; then
+                #   IBM i5/OS (aka OS/400) with PASE (Portable Application Solutions Environment)
+                cpu_arch=powerpc
             fi
             if [ -x /usr/bin/oslevel ]; then
                 os_level=`/usr/bin/oslevel`
             else
-                os_level="`uname -r`.`uname -v`"
+                os_level="`uname -v`.`uname -r`"
             fi
             os_level=`echo "${os_level}" |\
                       sed -e 's;^\([0-9][0-9]*\.[0-9][0-9]*\)\(\.[0-9][0-9]*\)\(.*\)$;<\1>\2[\3];' \
@@ -2880,7 +2894,7 @@ platform )
             AT="${cpu_arch}"
             AP="${AT}"
             AC="${AP}"
-            ST="[IBM ]AIX ${os_level}"
+            ST="[IBM ]<AIX >${os_level}"
             SP="${ST}"
             case "${os_level}" in
                 [12]* ) SC="SVR2" ;;
@@ -3048,7 +3062,7 @@ platform )
 arx )
     ##
     ##  arx -- Extended archive command
-    ##  Copyright (c) 1999-2004 Ralf S. Engelschall <rse@engelschall.com>
+    ##  Copyright (c) 1999-2005 Ralf S. Engelschall <rse@engelschall.com>
     ##
 
     ar_prg="$opt_C"
@@ -3057,7 +3071,7 @@ arx )
     files="$*"
 
     #   walk through the file list and expand archives members
-    tmpdir=`echo $archive | sed -e 's;[^/]*$;.arx;'`
+    ar_tmpdir=`echo $archive | sed -e 's;[^/]*$;.arx;'`
     nfiles=''
     if [ ".$files" != . ]; then
         for file in $files; do
@@ -3067,13 +3081,13 @@ arx )
             fi
             case $file in
                 *.a )
-                    if [ ! -d $tmpdir ]; then
+                    if [ ! -d $ar_tmpdir ]; then
                         if [ ".$opt_t" = .yes ]; then
-                            echo "mkdir $tmpdir" 1>&2
+                            echo "mkdir $ar_tmpdir" 1>&2
                         fi
-                        mkdir $tmpdir
+                        mkdir $ar_tmpdir
                     fi
-                    case $tmpdir in
+                    case $ar_tmpdir in
                          .arx )
                              from="../$file"
                              ;;
@@ -3084,16 +3098,16 @@ arx )
                              ;;
                     esac
                     if [ ".$opt_t" = .yes ]; then
-                        echo "(cd $tmpdir && $ar_prg x $from)" 1>&2
+                        echo "(cd $ar_tmpdir && $ar_prg x $from)" 1>&2
                     fi
-                    (cd $tmpdir && eval $ar_prg x $from)
+                    (cd $ar_tmpdir && eval $ar_prg x $from)
                     if [ $? -ne 0 ]; then
                         echo "$msgprefix:Error: member extraction failed for archive: $file" 1>&2
                         shtool_exit 1
                     fi
                     for member in - `eval $ar_prg t $file | sed -e '/_\.SYMDEF/d'`; do
                         [ ".$member" = .- ] && continue
-                        nfiles="$nfiles $tmpdir/$member"
+                        nfiles="$nfiles $ar_tmpdir/$member"
                     done
                     ;;
                 * )
@@ -3114,11 +3128,11 @@ arx )
     fi
 
     #   cleanup and die gracefully
-    if [ -d $tmpdir ]; then
+    if [ -d $ar_tmpdir ]; then
         if [ ".$opt_t" = .yes ]; then
-            echo "rm -rf $tmpdir" 1>&2
+            echo "rm -rf $ar_tmpdir" 1>&2
         fi
-        rm -rf $tmpdir
+        rm -rf $ar_tmpdir
     fi
 
     shtool_exit 0
@@ -3127,7 +3141,7 @@ arx )
 slo )
     ##
     ##  slo -- Separate linker options by library class
-    ##  Copyright (c) 1998-2004 Ralf S. Engelschall <rse@engelschall.com>
+    ##  Copyright (c) 1998-2005 Ralf S. Engelschall <rse@engelschall.com>
     ##
 
     DIFS="$IFS"
@@ -3286,7 +3300,7 @@ slo )
 scpp )
     ##
     ##  scpp -- Sharing C Pre-Processor
-    ##  Copyright (c) 1999-2004 Ralf S. Engelschall <rse@engelschall.com>
+    ##  Copyright (c) 1999-2005 Ralf S. Engelschall <rse@engelschall.com>
     ##
 
     srcs="$*"
@@ -3506,7 +3520,7 @@ scpp )
 version )
     ##
     ##  version -- Maintain a version information file
-    ##  Copyright (c) 1994-2004 Ralf S. Engelschall <rse@engelschall.com>
+    ##  Copyright (c) 1994-2005 Ralf S. Engelschall <rse@engelschall.com>
     ##
 
     file="$1"
@@ -3801,7 +3815,7 @@ version )
 path )
     ##
     ##  path -- Deal with program paths
-    ##  Copyright (c) 1998-2004 Ralf S. Engelschall <rse@engelschall.com>
+    ##  Copyright (c) 1998-2005 Ralf S. Engelschall <rse@engelschall.com>
     ##
 
     namelist="$*"
